site_name: pyquadkey2
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Documentation:
      - 'Instantiation': 'instantiation.md'
      - 'Methods': 'methods.md'
  - GitHub: 'https://github.com/muety/pyquadkey2'
theme: 'readthedocs'